export default [
    {
        name: 'Germany',
        code: 'DE',
        emoji: '🇩🇪',
        unicode: 'U+1F1E9 U+1F1EA',
        image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DE.svg',
        nativeName: 'Deutschland',
        href: 'de',
    },
    {
        name: 'Turkey',
        code: 'TR',
        emoji: '🇹🇷',
        unicode: 'U+1F1F9 U+1F1F7',
        image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TR.svg',
        nativeName: 'Türkiye',
        href: 'tr',
    },
    {
        name: 'United Kingdom',
        code: 'GB',
        emoji: '🇬🇧',
        unicode: 'U+1F1EC U+1F1E7',
        image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GB.svg',
        nativeName: 'United Kingdom',
        href: 'en',
    },
    {
        name: 'France',
        code: 'FR',
        emoji: '🇫🇷',
        unicode: 'U+1F1EB U+1F1F7',
        image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FR.svg',
        nativeName: 'Français',
        href: 'fr',
    },
    {
        name: 'Italy',
        code: 'IT',
        emoji: '🇮🇹',
        unicode: 'U+1F1EE U+1F1F9',
        image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IT.svg',
        nativeName: 'Italiano',
        href: 'it',
    },
    {
        name: 'Spain',
        code: 'ES',
        emoji: '🇪🇸',
        unicode: 'U+1F1EA U+1F1F8',
        image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ES.svg',
        nativeName: 'España',
        href: 'es',
    },
    {
        name: 'Netherlands',
        code: 'NL',
        emoji: '🇳🇱',
        unicode: 'U+1F1F3 U+1F1F1',
        image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NL.svg',
        nativeName: 'Nederland',
        href: 'nl',
    },
] as const;
